import { Club } from '@/types';

export const SANTARÉM_CLUBS: Club[] = [
  {
    id: 'uniao-tomar',
    name: 'União Futebol Comércio e Indústria de Tomar',
    shortName: 'U. Tomar',
    initials: 'UFT',
    division: '1_divisao',
    primaryColor: '#dc2626',
    secondaryColor: '#ffffff',
    stadiumName: 'Estádio Municipal de Tomar',
    latitude: 39.6038,
    longitude: -8.4069,
  },
  {
    id: 'torres-novas',
    name: 'Clube Desportivo de Torres Novas',
    shortName: 'CD Torres Novas',
    initials: 'CDTN',
    division: '1_divisao',
    primaryColor: '#ca8a04',
    secondaryColor: '#1e3a8a',
    stadiumName: 'Estádio Municipal Dr. Alves Vieira',
    latitude: 39.4795,
    longitude: -8.5361,
  },
  {
    id: 'samora-correia',
    name: 'Sociedade Recreativa Operária Samorense',
    shortName: 'Samora Correia',
    initials: 'SROS',
    division: '1_divisao',
    primaryColor: '#16a34a',
    secondaryColor: '#ffffff',
    stadiumName: 'Campo da Murteira',
    latitude: 38.9328,
    longitude: -8.8687,
  },
  {
    id: 'abrantes-benfica',
    name: 'Sport Abrantes e Benfica',
    shortName: 'Abrantes e Benfica',
    initials: 'SAB',
    division: '1_divisao',
    primaryColor: '#dc2626',
    secondaryColor: '#ffffff',
    stadiumName: 'Estádio Municipal de Abrantes',
    latitude: 39.4633,
    longitude: -8.1983,
  },
  {
    id: 'riachense',
    name: 'Clube Atlético Riachense',
    shortName: 'Riachense',
    initials: 'CAR',
    division: '1_divisao',
    primaryColor: '#eab308',
    secondaryColor: '#000000',
    stadiumName: 'Campo Coronel Mário Cunha',
    latitude: 39.4452,
    longitude: -8.4831,
  },
  {
    id: 'fatima',
    name: 'Centro Desportivo de Fátima',
    shortName: 'CD Fátima',
    initials: 'CDF',
    division: '1_divisao',
    primaryColor: '#b91c1c',
    secondaryColor: '#ffffff',
    stadiumName: 'Estádio Papa Francisco',
    latitude: 39.6172,
    longitude: -8.6534,
  },
  {
    id: 'atalaiense',
    name: 'União Desportiva Atalaiense',
    shortName: 'UD Atalaiense',
    initials: 'UDA',
    division: '2_divisao_b',
    primaryColor: '#15803d',
    secondaryColor: '#ffffff',
    stadiumName: 'Campo Dr. Mário Bento',
    latitude: 39.4998,
    longitude: -8.4412,
  },
  {
    id: 'ferreira-zezere',
    name: 'Sport Club Ferreira do Zêzere',
    shortName: 'Ferreira do Zêzere',
    initials: 'SCFZ',
    division: '1_divisao',
    primaryColor: '#eab308',
    secondaryColor: '#15803d',
    stadiumName: 'Campo Eng. Lopo de Carvalho',
    latitude: 39.6917,
    longitude: -8.2908,
  },
  {
    id: 'alpiarca',
    name: 'Águias de Alpiarça',
    shortName: 'Águias Alpiarça',
    initials: 'CDAA',
    division: '2_divisao_a',
    primaryColor: '#0284c7',
    secondaryColor: '#ffffff',
    stadiumName: 'Estádio Municipal de Alpiarça',
    latitude: 39.2612,
    longitude: -8.5833,
  },
];